name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  release:
    uses: RRZE-Webteam/FAU-Studium-Common/.github/workflows/build.yml@main
    secrets:
      DEPLOYBOT_EMAIL: ${{ secrets.DEPLOYBOT_EMAIL }}
      DEPLOYBOT_USER: ${{ secrets.DEPLOYBOT_USER }}
