name: Quality assurance PHP
on:
  pull_request:
    branches:
      - main
      - dev
    paths:
      - '**.php'
      - 'composer.*'
      - 'phpcs.*'
      - 'phpunit.*'
      - 'psalm.*'
jobs:
  coding-standards-analysis-php:
    uses: inpsyde/reusable-workflows/.github/workflows/coding-standards-php.yml@main
    secrets:
      COMPOSER_AUTH_JSON: ${{ secrets.PACKAGIST_AUTH_JSON }}
    with:
      PHP_VERSION: "8.2"
  static-code-analysis-php:
    uses: inpsyde/reusable-workflows/.github/workflows/static-analysis-php.yml@main
    secrets:
      COMPOSER_AUTH_JSON: ${{ secrets.PACKAGIST_AUTH_JSON }}
    with:
      PHP_VERSION: "8.2"
  lint-php:
    uses: inpsyde/reusable-workflows/.github/workflows/lint-php.yml@main
    strategy:
      matrix:
        php: [ "8.2", "8.3" ]
    with:
      PHP_VERSION: ${{ matrix.php }}
  tests-unit-php:
    needs: [ coding-standards-analysis-php, static-code-analysis-php ]
    uses: inpsyde/reusable-workflows/.github/workflows/tests-unit-php.yml@main
    strategy:
      matrix:
        php: [ "8.2", "8.3" ]
    with:
      PHP_VERSION: ${{ matrix.php }}
